/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CultivoController;
import javax.swing.JOptionPane;

/**
 *
 * @author omaci
 */
public class ActualizarCultivo extends javax.swing.JFrame {

    /**
     * Creates new form CrearCliente
     */
  
    private Runnable onCultivoActualizado;
  
    public ActualizarCultivo(
            int idCultivo,
            String nombreEspecie,
            String variedad,
            String descripcion,
            Runnable onCultivoActualizado) {

        initComponents();

        // Guardar el callback
        this.onCultivoActualizado = onCultivoActualizado;

        // Llenar los campos con los datos recibidos
        id__cul.setText(String.valueOf(idCultivo));
        id__cul.setEditable(false);
        this.especienom.setText(nombreEspecie);
        this.vari.setText(variedad);
        this.descrip.setText(descripcion);}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        descrip = new javax.swing.JTextField();
        especienom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        vari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        id__cul = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 180, 60));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar cultivo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 390, 60));

        jLabel6.setText("Descripcion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripActionPerformed(evt);
            }
        });
        jPanel1.add(descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 180, 40));

        especienom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especienomActionPerformed(evt);
            }
        });
        jPanel1.add(especienom, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 180, 40));

        jLabel5.setText("Nombre de la especie");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        vari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variActionPerformed(evt);
            }
        });
        jPanel1.add(vari, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 180, 40));

        jLabel7.setText("Variedad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        id__cul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__culActionPerformed(evt);
            }
        });
        jPanel1.add(id__cul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 40));

        jLabel8.setText("Id del cultivo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        // Obtener los valores del formulario
        int idCultivo = Integer.parseInt(id__cul.getText().trim());
        String nombreEspecie = especienom.getText().trim();
        String variedad = vari.getText().trim();
        String descripcion = descrip.getText().trim();;

        // Validar campos obligatorios
        if (nombreEspecie.isEmpty() || variedad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nombre de especie y variedad son obligatorios.");
            return;
        }

        // Llamar al controlador
        CultivoController cultivoController = new CultivoController();
        boolean actualizado = cultivoController.actualizarCultivo(
                idCultivo,
                nombreEspecie,
                variedad,
                descripcion
        );

        // Resultado
        if (actualizado) {
            JOptionPane.showMessageDialog(this, "✅ Cultivo actualizado correctamente.");

            if (onCultivoActualizado != null) {
                onCultivoActualizado.run(); // refresca tabla
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Error al actualizar el cultivo.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar el cultivo.");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripActionPerformed

    private void especienomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especienomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especienomActionPerformed

    private void variActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_variActionPerformed

    private void id__culActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__culActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__culActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarCultivo(0,"","","",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descrip;
    private javax.swing.JTextField especienom;
    private javax.swing.JTextField id__cul;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField vari;
    // End of variables declaration//GEN-END:variables
}
