/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.FuncionarioICAController;
import javax.swing.JOptionPane;

/**
 *
 * @author omaci
 */
public class ActualizarFuncionarioICA extends javax.swing.JFrame {

    /**
     * Creates new form CrearCliente
     */
  
    private Runnable onFuncionarioActualizado;
  
    public ActualizarFuncionarioICA(
            int idFuncionario,
            long numeroIdentificacion,
            String tipoIdentificacion,
            String primerNombre,
            String segundoNombre,
            String primerApellido,
            String segundoApellido,
            long celular,
            String correo,
            String estado,
            Runnable onFuncionarioActualizado) {

        initComponents();

        // Guardar el callback
        this.onFuncionarioActualizado = onFuncionarioActualizado;

        // Llenar los campos con los datos recibidos
        this.id__funcionario.setText(String.valueOf(idFuncionario));
        this.cedula.setText(String.valueOf(numeroIdentificacion));
        tipocedula.addItem("CC"); tipocedula.addItem("CC"); tipocedula.addItem("CE"); tipocedula.addItem("PA");tipocedula.addItem("NIT"); tipocedula.setSelectedItem(tipoIdentificacion);
        this.PriNombre.setText(primerNombre);
        this.segNombre.setText(segundoNombre);
        this.priApellido.setText(primerApellido);
        this.segApellido.setText(segundoApellido);
        this.telefono.setText(String.valueOf(celular));
        this.correoo.setText(correo);
        estadooo.addItem("ACTIVO"); estadooo.addItem("INACTIVO"); estadooo.setSelectedItem(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        actualizarTec = new javax.swing.JButton();
        id__funcionario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        estadooo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tipocedula = new javax.swing.JComboBox<>();
        PriNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        segNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        segApellido = new javax.swing.JTextField();
        priApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        correoo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizarTec.setText("Actualizar");
        actualizarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTecActionPerformed(evt);
            }
        });
        jPanel1.add(actualizarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 170, 60));

        id__funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__funcionarioActionPerformed(evt);
            }
        });
        jPanel1.add(id__funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar funcionario ICA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 580, 60));

        jPanel1.add(estadooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 180, 40));

        jLabel6.setText("Estado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        jPanel1.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 180, 40));

        jLabel2.setText("Numero de identificacion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel3.setText("Tipo de identificacion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        tipocedula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion...", "CC", "CE", "PA", "NIT" }));
        jPanel1.add(tipocedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 180, 40));
        jPanel1.add(PriNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 180, 40));

        jLabel4.setText("Primer nombre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        segNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segNombreActionPerformed(evt);
            }
        });
        jPanel1.add(segNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 180, 40));

        jLabel5.setText("Segundo nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel7.setText("Segundo Apellido");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        segApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(segApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 180, 40));

        priApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(priApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 180, 40));

        jLabel8.setText("Primer apellido");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        correoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correooActionPerformed(evt);
            }
        });
        jPanel1.add(correoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 180, 40));

        jLabel10.setText("Correo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 180, 40));

        jLabel9.setText("Celular");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        jLabel11.setText("Numero de identificacion");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTecActionPerformed
    try {
        // Obtener los valores del formulario
        int idFuncionario = Integer.parseInt(id__funcionario.getText().trim());
        long numeroIdentificacion = Long.parseLong(cedula.getText().trim());
        String tipoIdentificacion = (String) tipocedula.getSelectedItem();
        String primerNombre = PriNombre.getText().trim();
        String segundoNombre = segNombre.getText().trim();
        String primerApellido = priApellido.getText().trim();
        String segundoApellido = segApellido.getText().trim();
        long celular = Long.parseLong(telefono.getText().trim());
        String correo = correoo.getText().trim();
        String estado = (String) estadooo.getSelectedItem();

        // Validar campos obligatorios
        if (tipoIdentificacion.isEmpty() || primerNombre.isEmpty() || primerApellido.isEmpty() || correo.isEmpty() || estado.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Todos los campos obligatorios deben estar llenos.");
            return;
        }

        // Llamar al controlador
        FuncionarioICAController funcionarioICAController = new FuncionarioICAController();
        boolean actualizado = funcionarioICAController.actualizarFuncionario(
                idFuncionario,
                numeroIdentificacion,
                tipoIdentificacion,
                primerNombre,
                segundoNombre,
                primerApellido,
                segundoApellido,
                celular,
                correo,
                estado
        );

        // Resultado
        if (actualizado) {
            JOptionPane.showMessageDialog(this, "✅ Funcionario actualizado correctamente.");

            if (onFuncionarioActualizado != null) {
                onFuncionarioActualizado.run(); // refresca tabla
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Error al actualizar el funcionario.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La identificación y el celular deben ser valores numéricos.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar el productor.");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_actualizarTecActionPerformed

    private void id__funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__funcionarioActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void segNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segNombreActionPerformed

    private void segApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segApellidoActionPerformed

    private void priApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priApellidoActionPerformed

    private void correooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correooActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarFuncionarioICA(0,0L,"","","","","",0L,"","",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PriNombre;
    private javax.swing.JButton actualizarTec;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField correoo;
    private javax.swing.JComboBox<String> estadooo;
    private javax.swing.JTextField id__funcionario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField priApellido;
    private javax.swing.JTextField segApellido;
    private javax.swing.JTextField segNombre;
    private javax.swing.JTextField telefono;
    private javax.swing.JComboBox<String> tipocedula;
    // End of variables declaration//GEN-END:variables
}
