/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PredioController;
import modelo.LugarProduccion;
import modelo.LugarProduccionDAO;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import modelo.ProductorDAO;


/**
 *
 * @author omaci
 */
public class ActualizarPredio extends javax.swing.JFrame {

    /**
     * Creates new form CrearCliente
     */
  
    private Runnable onPredioActualizado;
    private final List<Integer> lugarProIds = new ArrayList<>();
  
    public ActualizarPredio(
            int idPredio,
            String nombrePredio,
            double areaTotal,
            String nombrePropietario,
            String direccion,
            double coordenadasLat,
            double coordenadasLon,
            int idLugar,
            String estado,
            Runnable onPredioActualizado) {

        initComponents();
        setLocationRelativeTo(null);

        // Guardar callback para refrescar tabla
        this.onPredioActualizado = onPredioActualizado;

        cargarCombosSeleccionando(idLugar);
        
        // Llenar los campos con los datos del predio
        this.id__predio.setText(String.valueOf(idPredio));
        id__predio.setEditable(false);
        this.nombrePR.setText(nombrePredio);
        this.AreaT.setText(String.valueOf(areaTotal));
        this.NombrePropi.setText(nombrePropietario);
        this.Direccionn.setText(direccion);
        this.latitud.setText(String.valueOf(coordenadasLat));
        this.longitud.setText(String.valueOf(coordenadasLon));
        cboEstado.addItem("ACTIVO"); cboEstado.addItem("INACTIVO"); cboEstado.setSelectedItem(estado);
    }
    
    private void cargarCombosSeleccionando(int idLugar) {
        cboLugar1.removeAllItems();
        lugarProIds.clear();

        // lugares
        LugarProduccionDAO tdao = new LugarProduccionDAO();
        int idxSelP = -1; int idx = 0;
        for (LugarProduccion t : tdao.listarLugaresConProductor()) {
            cboLugar1.addItem(t.getDepartamento());
            lugarProIds.add(t.getId_lugar());
            if (t.getId_lugar()== idLugar) idxSelP = idx;
            idx++;
        }
        if (idxSelP >= 0) cboLugar1.setSelectedIndex(idxSelP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        actualizarTec = new javax.swing.JButton();
        id__predio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nombrePR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NombrePropi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        latitud = new javax.swing.JTextField();
        AreaT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        longitud = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Direccionn = new javax.swing.JTextField();
        cboEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboLugar1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizarTec.setText("Actualizar");
        actualizarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTecActionPerformed(evt);
            }
        });
        jPanel1.add(actualizarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 170, 60));

        id__predio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__predioActionPerformed(evt);
            }
        });
        jPanel1.add(id__predio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 180, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar predio");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 390, 60));

        nombrePR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePRActionPerformed(evt);
            }
        });
        jPanel1.add(nombrePR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 180, 40));

        jLabel2.setText("Id del predio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel4.setText("Nombre del propietario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        jPanel1.add(NombrePropi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, 40));

        jLabel7.setText("Cordenadas (Latitud)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        latitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latitudActionPerformed(evt);
            }
        });
        jPanel1.add(latitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 180, 40));

        AreaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTActionPerformed(evt);
            }
        });
        jPanel1.add(AreaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 180, 40));

        jLabel3.setText("Area total (Hectarioas)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel8.setText("Cordenadas (Longitud)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        longitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudActionPerformed(evt);
            }
        });
        jPanel1.add(longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 180, 40));

        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        Direccionn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionnActionPerformed(evt);
            }
        });
        jPanel1.add(Direccionn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 180, 40));

        jPanel1.add(cboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 180, 40));

        jLabel6.setText("Estado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel9.setText("Nombre del predio");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jPanel1.add(cboLugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 180, 40));

        jLabel10.setText("lugar de produccion");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTecActionPerformed
    try {
        // Obtener los valores del formulario
        int idPredio = Integer.parseInt(id__predio.getText().trim());
        String nombrePredio = nombrePR.getText().trim();
        double areaTotal = Double.parseDouble(AreaT.getText().trim());
        String nombrePropietario = NombrePropi.getText().trim();
        String direccion = Direccionn.getText().trim();
        double coordenadasLat = Double.parseDouble(latitud.getText().trim());
        double coordenadasLon = Double.parseDouble(longitud.getText().trim());
        String estado = (String) cboEstado.getSelectedItem();

        // Validar campos obligatorios
        if (nombrePredio.isEmpty() || nombrePropietario.isEmpty() || direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor completa todos los campos obligatorios.",
                "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idxP = cboLugar1.getSelectedIndex();
        if (idxP < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione Lugar de produccion.");
            return;
        }
        int idLugar = lugarProIds.get(idxP);

        // Crear el controlador
        PredioController predioController = new PredioController();

        // Llamar al método de actualización
        boolean actualizado = predioController.actualizarPredio(
                idPredio, 
                nombrePredio,
                areaTotal,
                nombrePropietario,
                direccion,
                coordenadasLat,
                coordenadasLon,
                idLugar,
                estado
        );

        // Mostrar resultado
        if (actualizado) {
            JOptionPane.showMessageDialog(this,
                "✅ Predio actualizado correctamente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);

            if (onPredioActualizado != null) {
                onPredioActualizado.run(); // refrescar tabla
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                "❌ Error al actualizar el predio.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Error: Los campos numéricos deben contener solo números.",
            "Error de formato", JOptionPane.ERROR_MESSAGE);
        System.out.println("❌ Error de número: " + e.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
            "Ocurrió un error al actualizar el predio.",
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_actualizarTecActionPerformed

    private void id__predioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__predioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__predioActionPerformed

    private void nombrePRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePRActionPerformed

    private void latitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudActionPerformed

    private void AreaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaTActionPerformed

    private void longitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudActionPerformed

    private void DireccionnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarPredio(0,"",0.0,"","",0.0,0.0,0,"",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaT;
    private javax.swing.JTextField Direccionn;
    private javax.swing.JTextField NombrePropi;
    private javax.swing.JButton actualizarTec;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboLugar1;
    private javax.swing.JTextField id__predio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField latitud;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField nombrePR;
    // End of variables declaration//GEN-END:variables
}
