/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.util.ArrayList;
import java.util.List;

import controlador.ObservacionesController;
import controlador.FuncionarioICAController;
import controlador.InspeccionFitosanitariaController;
import modelo.InspeccionFitosanitaria;
import modelo.FuncionarioICA;

/**
 *
 * @author omaci
 */
public class ActualizarObservacion extends javax.swing.JFrame {

    private ObservacionesController observacionesController;
    private Runnable onObservacionActualizada;

    private final List<Integer> inspeccionIds  = new ArrayList<>();
    private final List<Integer> funcionarioIds = new ArrayList<>();

    private static final DateTimeFormatter FMT_YMD =
        DateTimeFormatter.ofPattern("uuuu-MM-dd").withResolverStyle(ResolverStyle.STRICT);
  
    public ActualizarObservacion(int idObservacion,
                                 String fechaObs,
                                 String textoObs,
                                 int idInspeccionSel,
                                 int idFuncionarioSel, // si no lo tienes, pasa 0
                                 Runnable onObservacionActualizada) {
        initComponents();
        setLocationRelativeTo(null);
        this.observacionesController = new ObservacionesController();
        this.onObservacionActualizada = onObservacionActualizada;

        cargarCombosSeleccionando(idInspeccionSel, idFuncionarioSel);

        txtObsercacion.setText(String.valueOf(idObservacion));
        txtObsercacion.setEditable(false);
        txtFecha.setText(fechaObs != null ? fechaObs : "");
        txtObsercaiocnes.setText(textoObs != null ? textoObs : "");
    }

    /* ===================== VALIDAR FECHA ===================== */

    private boolean validarFechaCampo(JTextField campo, String etiqueta) {
        String s = campo.getText().trim();
        if (s.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "La " + etiqueta + " es obligatoria.",
                "Fecha inválida",
                JOptionPane.WARNING_MESSAGE
            );
            campo.requestFocus();
            return false;
        }
        try {
            LocalDate.parse(s, FMT_YMD);
            return true;
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this,
                "Formato inválido en " + etiqueta + ": \"" + s + "\".\n" +
                "Usa yyyy-MM-dd (ej. 2025-11-09).",
                "Fecha inválida",
                JOptionPane.WARNING_MESSAGE
            );
            campo.requestFocus();
            return false;
        }
    }
    
    private void cargarCombosSeleccionando(int idInspeccionSel, int idFuncionarioSel) {
        cboInspeccion.removeAllItems();
        cboFuncionario.removeAllItems();
        inspeccionIds.clear();
        funcionarioIds.clear();

        // Inspecciones
        InspeccionFitosanitariaController inspCtrl = new InspeccionFitosanitariaController();
        int idxSelInsp = -1, idx = 0;
        for (InspeccionFitosanitaria insp : inspCtrl.listarConTecnicoEIncidencia()) {
            String etiqueta = "ID " + insp.getId_inspeccion()
                            + " - Lote " + insp.getNumero_lote()
                            + " - " + insp.getFecha_inspeccion();
            cboInspeccion.addItem(etiqueta);
            inspeccionIds.add(insp.getId_inspeccion());
            if (insp.getId_inspeccion() == idInspeccionSel) idxSelInsp = idx;
            idx++;
        }
        if (idxSelInsp >= 0) cboInspeccion.setSelectedIndex(idxSelInsp);

        // Funcionarios
        FuncionarioICAController funcCtrl = new FuncionarioICAController();
        int idxSelFunc = -1; 
        idx = 0;
        for (FuncionarioICA f : funcCtrl.obtenerFuncionariosActivos()) {
            String nombreCompleto = f.getPrimer_nombre() + " " + f.getPrimer_apellido();
            cboFuncionario.addItem(nombreCompleto);
            funcionarioIds.add(f.getId_funcionario());
            if (f.getId_funcionario() == idFuncionarioSel) idxSelFunc = idx;
            idx++;
        }
        if (idxSelFunc >= 0) cboFuncionario.setSelectedIndex(idxSelFunc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtObsercacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObsercaiocnes = new javax.swing.JTextArea();
        cboInspeccion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboFuncionario = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 180, 60));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar observacion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 500, 60));

        txtObsercacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObsercacionActionPerformed(evt);
            }
        });
        jPanel1.add(txtObsercacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 180, 40));

        jLabel8.setText("Id de la observacion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 180, 40));

        jLabel10.setText("Fecha de la observacion");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel7.setText("Observaciones");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtObsercaiocnes.setColumns(20);
        txtObsercaiocnes.setRows(5);
        jScrollPane1.setViewportView(txtObsercaiocnes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 420, 120));

        jPanel1.add(cboInspeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, 40));

        jLabel9.setText("Numero de la inspeccion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jPanel1.add(cboFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 180, 40));

        jLabel6.setText("Funcionario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtObsercacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObsercacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObsercacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int idObs   = Integer.parseInt(txtObsercacion.getText().trim());
            String fecha = txtFecha.getText().trim();
            String texto = txtObsercaiocnes.getText().trim();

            if (!validarFechaCampo(txtFecha, "Fecha de la observación")) return;
            if (texto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El texto de la observación es obligatorio.");
                return;
            }

            int idxInsp = cboInspeccion.getSelectedIndex();
            int idxFunc = cboFuncionario.getSelectedIndex();
            if (idxInsp < 0 || idxFunc < 0) {
                JOptionPane.showMessageDialog(this, "Seleccione inspección y funcionario.");
                return;
            }

            int idInspeccion  = inspeccionIds.get(idxInsp);
            int idFuncionario = funcionarioIds.get(idxFunc);

            String error = observacionesController.actualizar(
                    idObs,
                    fecha,
                    texto,
                    idInspeccion,
                    idFuncionario
            );

            if (error == null) {
                JOptionPane.showMessageDialog(this, "✅ Observación actualizada.");
                if (onObservacionActualizada != null) onObservacionActualizada.run();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, error, "Error al actualizar", JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "ID debe ser entero.");
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, iae.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar.");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarObservacion(0, "", "", 0, 0, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboFuncionario;
    private javax.swing.JComboBox<String> cboInspeccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtObsercacion;
    private javax.swing.JTextArea txtObsercaiocnes;
    // End of variables declaration//GEN-END:variables
}
