/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ProductorController;
import javax.swing.JOptionPane;

/**
 *
 * @author omaci
 */
public class ActualizarProductor extends javax.swing.JFrame {

    /**
     * Creates new form CrearCliente
     */
  
  private Runnable onProductorActualizado;
  
public ActualizarProductor(
        int idProductor,
        long numeroIdentificacion,
        String tipoIdentificacion,
        String primerNombre,
        String segundoNombre,
        String primerApellido,
        String segundoApellido,
        String direccion,
        long celular,
        String correo,
        String estado,
        Runnable onProductorActualizado) {

    initComponents();

    // Guardar el callback
    this.onProductorActualizado = onProductorActualizado;

    // Llenar los campos con los datos recibidos
    this.id__productorA.setText(String.valueOf(idProductor));
    this.cedula.setText(String.valueOf(numeroIdentificacion));
    this.tipoCedula.setText(tipoIdentificacion);
    this.PriNombre.setText(primerNombre);
    this.segNombre.setText(segundoNombre);
    this.priApellido.setText(primerApellido);
    this.segApellido.setText(segundoApellido);
    this.direccion.setText(direccion);
    this.telefono.setText(String.valueOf(celular));
    this.correoo.setText(correo);
    this.estadooo.setText(estado);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        id__productorA = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        tipoCedula = new javax.swing.JTextField();
        PriNombre = new javax.swing.JTextField();
        segNombre = new javax.swing.JTextField();
        priApellido = new javax.swing.JTextField();
        segApellido = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        estadooo = new javax.swing.JTextField();
        correoo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 170, 60));

        id__productorA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__productorAActionPerformed(evt);
            }
        });
        jPanel1.add(id__productorA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, 40));

        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        jPanel1.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 180, 40));

        tipoCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(tipoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 180, 40));
        jPanel1.add(PriNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 180, 40));

        segNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segNombreActionPerformed(evt);
            }
        });
        jPanel1.add(segNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 40));

        priApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(priApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 180, 40));

        segApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(segApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 180, 40));

        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 180, 40));

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 40));

        estadooo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoooActionPerformed(evt);
            }
        });
        jPanel1.add(estadooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 180, 40));

        correoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correooActionPerformed(evt);
            }
        });
        jPanel1.add(correoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 180, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar productor");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 460, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        // Obtener los valores del formulario
        int idProductor = Integer.parseInt(id__productorA.getText().trim());
        long numeroIdentificacion = Long.parseLong(cedula.getText().trim());
        String tipoIdentificacion = tipoCedula.getText().trim();
        String primerNombre = PriNombre.getText().trim();
        String segundoNombre = segNombre.getText().trim();
        String primerApellido = priApellido.getText().trim();
        String segundoApellido = segApellido.getText().trim();
        String direccionTxt = direccion.getText().trim();
        long celular = Long.parseLong(telefono.getText().trim());
        String correo = correoo.getText().trim();
        String estado = estadooo.getText().trim();

        // Validar campos obligatorios
        if (tipoIdentificacion.isEmpty() || primerNombre.isEmpty() || primerApellido.isEmpty() ||
            direccionTxt.isEmpty() || correo.isEmpty() || estado.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Todos los campos obligatorios deben estar llenos.");
            return;
        }

        // Llamar al controlador
        ProductorController productorController = new ProductorController();
        boolean actualizado = productorController.actualizarProductor(
                idProductor,
                numeroIdentificacion,
                tipoIdentificacion,
                primerNombre,
                segundoNombre,
                primerApellido,
                segundoApellido,
                direccionTxt,
                celular,
                correo,
                estado
        );

        // Resultado
        if (actualizado) {
            JOptionPane.showMessageDialog(this, "✅ Productor actualizado correctamente.");

            if (onProductorActualizado != null) {
                onProductorActualizado.run(); // refresca tabla
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Error al actualizar el productor.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La identificación y el celular deben ser valores numéricos.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar el productor.");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id__productorAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__productorAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__productorAActionPerformed

    private void tipoCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCedulaActionPerformed

    private void segNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segNombreActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void priApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priApellidoActionPerformed

    private void segApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segApellidoActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void estadoooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoooActionPerformed

    private void correooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correooActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarProductor(0,0L,"","","","","","",0L,"","",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PriNombre;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField correoo;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField estadooo;
    private javax.swing.JTextField id__productorA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField priApellido;
    private javax.swing.JTextField segApellido;
    private javax.swing.JTextField segNombre;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField tipoCedula;
    // End of variables declaration//GEN-END:variables
}
