/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.LugarProduccionController;
import javax.swing.JOptionPane;

/**
 *
 * @author omaci
 */
public class ActualizarLugarPro extends javax.swing.JFrame {

    /**
     * Creates new form CrearCliente
     */
  
    private Runnable onLugarProActualizado;
  
    public ActualizarLugarPro(
            int idLugar,
            String departamento,
            String municipio,
            String vereda,
            int cantidadMaxima,
            int idProductor,
            Runnable onLugarProActualizado) {

        initComponents();

        // Guardar callback para refrescar tabla al actualizar
        this.onLugarProActualizado = onLugarProActualizado;

        // Llenar los campos con los datos del lugar de producción
        this.id__lugar.setText(String.valueOf(idLugar));
        this.departamentoo.setText(departamento);
        this.municipioo.setText(municipio);
        this.veredaa.setText(vereda);
        this.cantidad.setText(String.valueOf(cantidadMaxima));
        this.id__productor.setText(String.valueOf(idProductor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        actualizarTec = new javax.swing.JButton();
        id__lugar = new javax.swing.JTextField();
        departamentoo = new javax.swing.JTextField();
        municipioo = new javax.swing.JTextField();
        veredaa = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        id__productor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizarTec.setText("Actualizar");
        actualizarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTecActionPerformed(evt);
            }
        });
        jPanel1.add(actualizarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 170, 60));

        id__lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__lugarActionPerformed(evt);
            }
        });
        jPanel1.add(id__lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, 40));

        departamentoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentooActionPerformed(evt);
            }
        });
        jPanel1.add(departamentoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 180, 40));

        municipioo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipiooActionPerformed(evt);
            }
        });
        jPanel1.add(municipioo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, 40));
        jPanel1.add(veredaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 180, 40));

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, 40));

        id__productor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__productorActionPerformed(evt);
            }
        });
        jPanel1.add(id__productor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 180, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar lugar de produccion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 680, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTecActionPerformed
    try {
        // Obtener los valores del formulario
        int idLugar = Integer.parseInt(id__lugar.getText().trim());
        String departamento = departamentoo.getText().trim();
        String municipio = municipioo.getText().trim();
        String vereda = veredaa.getText().trim();
        int cantidadMaxima = Integer.parseInt(cantidad.getText().trim());
        int idProductor = Integer.parseInt(id__productor.getText().trim());

        // Validar campos obligatorios
        if (departamento.isEmpty() || municipio.isEmpty() || vereda.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor completa todos los campos obligatorios.",
                "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Crear el controlador
        LugarProduccionController lugarProduccionController = new LugarProduccionController();

        // Llamar al método de actualización
        boolean actualizado = lugarProduccionController.actualizarLugarProduccion(
            idLugar, departamento, municipio, vereda, cantidadMaxima, idProductor
        );

        // Mostrar resultado
        if (actualizado) {
            JOptionPane.showMessageDialog(this,
                "✅ Lugar de producción actualizado correctamente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);

            if (onLugarProActualizado != null) {
                onLugarProActualizado.run(); // refrescar tabla
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                "❌ Error al actualizar el lugar de producción.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Error: Los campos numéricos deben contener solo números.",
            "Error de formato", JOptionPane.ERROR_MESSAGE);
        System.out.println("❌ Error de número: " + e.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
            "Ocurrió un error al actualizar el lugar de producción.",
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_actualizarTecActionPerformed

    private void id__lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__lugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__lugarActionPerformed

    private void municipiooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipiooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipiooActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void departamentooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentooActionPerformed

    private void id__productorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__productorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__productorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarLugarPro(0,"","","",0,0,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarTec;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField departamentoo;
    private javax.swing.JTextField id__lugar;
    private javax.swing.JTextField id__productor;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField municipioo;
    private javax.swing.JTextField veredaa;
    // End of variables declaration//GEN-END:variables
}
