/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.FuncionarioICAController;
import javax.swing.JOptionPane;

/**
 *
 * @author omaci
 */
public class ActualizarFuncionarioICA extends javax.swing.JFrame {

    /**
     * Creates new form CrearCliente
     */
  
    private Runnable onFuncionarioActualizado;
  
    public ActualizarFuncionarioICA(
            int idFuncionario,
            long numeroIdentificacion,
            String tipoIdentificacion,
            String primerNombre,
            String segundoNombre,
            String primerApellido,
            String segundoApellido,
            long celular,
            String correo,
            String estado,
            Runnable onFuncionarioActualizado) {

        initComponents();

        // Guardar el callback
        this.onFuncionarioActualizado = onFuncionarioActualizado;

        // Llenar los campos con los datos recibidos
        this.id__funcionario.setText(String.valueOf(idFuncionario));
        this.cedula.setText(String.valueOf(numeroIdentificacion));
        this.tipoCedula.setText(tipoIdentificacion);
        this.PriNombre.setText(primerNombre);
        this.segNombre.setText(segundoNombre);
        this.priApellido.setText(primerApellido);
        this.segApellido.setText(segundoApellido);
        this.telefono.setText(String.valueOf(celular));
        this.correoo.setText(correo);
        this.estadooo.setText(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        actualizarTec = new javax.swing.JButton();
        id__funcionario = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        tipoCedula = new javax.swing.JTextField();
        PriNombre = new javax.swing.JTextField();
        segNombre = new javax.swing.JTextField();
        priApellido = new javax.swing.JTextField();
        segApellido = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        estadooo = new javax.swing.JTextField();
        correoo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizarTec.setText("Actualizar");
        actualizarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTecActionPerformed(evt);
            }
        });
        jPanel1.add(actualizarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 170, 60));

        id__funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__funcionarioActionPerformed(evt);
            }
        });
        jPanel1.add(id__funcionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, 40));

        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        jPanel1.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 180, 40));

        tipoCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(tipoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 180, 40));
        jPanel1.add(PriNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 180, 40));

        segNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segNombreActionPerformed(evt);
            }
        });
        jPanel1.add(segNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 40));

        priApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(priApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 180, 40));

        segApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(segApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 180, 40));

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 180, 40));

        estadooo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoooActionPerformed(evt);
            }
        });
        jPanel1.add(estadooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 180, 40));

        correoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correooActionPerformed(evt);
            }
        });
        jPanel1.add(correoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 180, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar funcionario ICA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 580, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTecActionPerformed
    try {
        // Obtener los valores del formulario
        int idFuncionario = Integer.parseInt(id__funcionario.getText().trim());
        long numeroIdentificacion = Long.parseLong(cedula.getText().trim());
        String tipoIdentificacion = tipoCedula.getText().trim();
        String primerNombre = PriNombre.getText().trim();
        String segundoNombre = segNombre.getText().trim();
        String primerApellido = priApellido.getText().trim();
        String segundoApellido = segApellido.getText().trim();
        long celular = Long.parseLong(telefono.getText().trim());
        String correo = correoo.getText().trim();
        String estado = estadooo.getText().trim();

        // Validar campos obligatorios
        if (tipoIdentificacion.isEmpty() || primerNombre.isEmpty() || primerApellido.isEmpty() || correo.isEmpty() || estado.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Todos los campos obligatorios deben estar llenos.");
            return;
        }

        // Llamar al controlador
        FuncionarioICAController funcionarioICAController = new FuncionarioICAController();
        boolean actualizado = funcionarioICAController.actualizarFuncionario(
                idFuncionario,
                numeroIdentificacion,
                tipoIdentificacion,
                primerNombre,
                segundoNombre,
                primerApellido,
                segundoApellido,
                celular,
                correo,
                estado
        );

        // Resultado
        if (actualizado) {
            JOptionPane.showMessageDialog(this, "✅ Funcionario actualizado correctamente.");

            if (onFuncionarioActualizado != null) {
                onFuncionarioActualizado.run(); // refresca tabla
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Error al actualizar el funcionario.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La identificación y el celular deben ser valores numéricos.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar el productor.");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_actualizarTecActionPerformed

    private void id__funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__funcionarioActionPerformed

    private void tipoCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCedulaActionPerformed

    private void segNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segNombreActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void priApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priApellidoActionPerformed

    private void segApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segApellidoActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void estadoooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoooActionPerformed

    private void correooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correooActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarFuncionarioICA(0,0L,"","","","","",0L,"","",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PriNombre;
    private javax.swing.JButton actualizarTec;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField correoo;
    private javax.swing.JTextField estadooo;
    private javax.swing.JTextField id__funcionario;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField priApellido;
    private javax.swing.JTextField segApellido;
    private javax.swing.JTextField segNombre;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField tipoCedula;
    // End of variables declaration//GEN-END:variables
}
