/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PlagaController;
import javax.swing.JOptionPane;

/**
 *
 * @author omaci
 */
public class ActualizarPlaga extends javax.swing.JFrame {

    /**
     * Creates new form CrearCliente
     */
  
  private Runnable onPlagaActualizado;
  
public ActualizarPlaga(
        int idPlaga,
        String nombreCientifico,
        String nombreComun,
        String descripcion,
        Runnable onPlagaActualizado) {

    initComponents();

    // Guardar el callback
    this.onPlagaActualizado = onPlagaActualizado;

    // Llenar los campos con los datos recibidos
    this.id__plagaA.setText(String.valueOf(idPlaga));
    this.nombrecien.setText(nombreCientifico);
    this.nombrecom.setText(nombreComun);
    this.desc.setText(descripcion);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        id__plagaA = new javax.swing.JTextField();
        nombrecien = new javax.swing.JTextField();
        nombrecom = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, 60));

        id__plagaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__plagaAActionPerformed(evt);
            }
        });
        jPanel1.add(id__plagaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, 40));

        nombrecien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecienActionPerformed(evt);
            }
        });
        jPanel1.add(nombrecien, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 180, 40));

        nombrecom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecomActionPerformed(evt);
            }
        });
        jPanel1.add(nombrecom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 180, 40));
        jPanel1.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 180, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar plaga");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 360, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        // Obtener los valores del formulario
        int idPlaga = Integer.parseInt(id__plagaA.getText().trim());
        String nombreCientifico = nombrecien.getText().trim();
        String nombreComun = nombrecom.getText().trim();
        String descripcion = desc.getText().trim();

        // Validar campos obligatorios
        if (nombreCientifico.isEmpty() || nombreComun.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Todos los campos obligatorios deben estar llenos.");
            return;
        }

        // Llamar al controlador
        PlagaController plagaController = new PlagaController();
        boolean actualizado = plagaController.actualizarPlaga(idPlaga, nombreCientifico, nombreComun, descripcion);

        // Resultado
        if (actualizado) {
            JOptionPane.showMessageDialog(this, "✅ Plaga actualizada correctamente.");

            if (onPlagaActualizado != null) {
                onPlagaActualizado.run(); // refresca tabla
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Error al actualizar la plaga.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La identificación y el celular deben ser valores numéricos.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar la plaga.");
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id__plagaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__plagaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__plagaAActionPerformed

    private void nombrecomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecomActionPerformed

    private void nombrecienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarPlaga(0,"","","",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField desc;
    private javax.swing.JTextField id__plagaA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrecien;
    private javax.swing.JTextField nombrecom;
    // End of variables declaration//GEN-END:variables
}
