/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.LugarProduccionController;
import java.util.ArrayList;
import modelo.Productor;
import modelo.ProductorDAO;
import javax.swing.*;
import java.util.List;

/**
 *
 * @author omaci
 */
public class ActualizarLugarPro extends javax.swing.JFrame {

    /**
     * Creates new form CrearCliente
     */
  
    private Runnable onLugarProActualizado;
    private final List<Integer> productorIds = new ArrayList<>();
  
    public ActualizarLugarPro(
            int idLugar,
            String departamento,
            String municipio,
            String vereda,
            int cantidadMaxima,
            int idProductor,
            Runnable onLugarProActualizado) {

        initComponents();
        setLocationRelativeTo(null);

        // Guardar callback para refrescar tabla al actualizar
        this.onLugarProActualizado = onLugarProActualizado;
        
        cargarCombosSeleccionando(idProductor);

        // Llenar los campos con los datos del lugar de producción
        this.id__lugar.setText(String.valueOf(idLugar));
        id__lugar.setEditable(false);
        this.departamentoo.setText(departamento);
        this.municipioo.setText(municipio);
        this.veredaa.setText(vereda);
        this.cantidad.setText(String.valueOf(cantidadMaxima));
    }
    
    private void cargarCombosSeleccionando(int idProductor) {
        cboProductor.removeAllItems();
        productorIds.clear();

        // Técnicos
        ProductorDAO tdao = new ProductorDAO();
        int idxSelP = -1; int idx = 0;
        for (Productor t : tdao.listarProductoresActivos()) {
            cboProductor.addItem(t.getPrimer_nombre());
            productorIds.add(t.getId_productor());
            if (t.getId_productor()== idProductor) idxSelP = idx;
            idx++;
        }
        if (idxSelP >= 0) cboProductor.setSelectedIndex(idxSelP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        actualizarTec = new javax.swing.JButton();
        id__lugar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        departamentoo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        veredaa = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        municipioo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboProductor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizarTec.setText("Actualizar");
        actualizarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTecActionPerformed(evt);
            }
        });
        jPanel1.add(actualizarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 170, 60));

        id__lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__lugarActionPerformed(evt);
            }
        });
        jPanel1.add(id__lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 180, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar lugar de produccion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 680, 60));

        departamentoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentooActionPerformed(evt);
            }
        });
        jPanel1.add(departamentoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 180, 40));

        jLabel2.setText("Id del lugar de produccion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel4.setText("Vereda");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));
        jPanel1.add(veredaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 180, 40));

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 180, 40));

        jLabel5.setText("Cantidad maxima");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        municipioo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipiooActionPerformed(evt);
            }
        });
        jPanel1.add(municipioo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, 40));

        jLabel3.setText("Municipio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jPanel1.add(cboProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 180, 40));

        jLabel6.setText("Productor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        jLabel7.setText("Departamento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTecActionPerformed
    try {
        // Obtener los valores del formulario
        int idLugar = Integer.parseInt(id__lugar.getText().trim());
        String departamento = departamentoo.getText().trim();
        String municipio = municipioo.getText().trim();
        String vereda = veredaa.getText().trim();
        int cantidadMaxima = Integer.parseInt(cantidad.getText().trim());

        // Validar campos obligatorios
        if (departamento.isEmpty() || municipio.isEmpty() || vereda.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor completa todos los campos obligatorios.",
                "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cantidadMaxima <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad máxima debe ser > 0.");
            return;
        }

        int idxP = cboProductor.getSelectedIndex();
        if (idxP < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione productor.");
            return;
        }

        int idProductor = productorIds.get(idxP);


        // Crear el controlador
        LugarProduccionController lugarProduccionController = new LugarProduccionController();

        // Llamar al método de actualización
        boolean actualizado = lugarProduccionController.actualizarLugar(
            idLugar, departamento, municipio, vereda, cantidadMaxima, idProductor
        );

        // Mostrar resultado
        if (actualizado) {
            JOptionPane.showMessageDialog(this,
                "✅ Lugar de producción actualizado correctamente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);

            if (onLugarProActualizado != null) {
                onLugarProActualizado.run(); // refrescar tabla
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                "❌ Error al actualizar el lugar de producción.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Error: Los campos numéricos deben contener solo números.",
            "Error de formato", JOptionPane.ERROR_MESSAGE);
        System.out.println("❌ Error de número: " + e.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
            "Ocurrió un error al actualizar el lugar de producción.",
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_actualizarTecActionPerformed

    private void id__lugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__lugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__lugarActionPerformed

    private void departamentooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentooActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void municipiooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipiooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipiooActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarLugarPro(0,"","","",0,0,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarTec;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> cboProductor;
    private javax.swing.JTextField departamentoo;
    private javax.swing.JTextField id__lugar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField municipioo;
    private javax.swing.JTextField veredaa;
    // End of variables declaration//GEN-END:variables
}
