/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PredioController;
import javax.swing.JOptionPane;

/**
 *
 * @author omaci
 */
public class ActualizarPredio extends javax.swing.JFrame {

    /**
     * Creates new form CrearCliente
     */
  
    private Runnable onPredioActualizado;
  
    public ActualizarPredio(
            int idPredio,
            String nombrePredio,
            double areaTotal,
            String nombrePropietario,
            String direccion,
            double coordenadasLat,
            double coordenadasLon,
            int idLugar,
            String estado,
            Runnable onPredioActualizado) {

        initComponents();

        // Guardar callback para refrescar tabla
        this.onPredioActualizado = onPredioActualizado;

        // Llenar los campos con los datos del predio
        this.id__predio.setText(String.valueOf(idPredio));
        this.nombrePRE.setText(nombrePredio);
        this.AreaTT.setText(String.valueOf(areaTotal));
        this.nombrePRO.setText(nombrePropietario);
        this.direccionn.setText(direccion);
        this.latitud.setText(String.valueOf(coordenadasLat));
        this.longitud.setText(String.valueOf(coordenadasLon));
        this.id__lugarrr.setText(String.valueOf(idLugar));
        this.estadoo.setText(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        actualizarTec = new javax.swing.JButton();
        id__predio = new javax.swing.JTextField();
        nombrePRE = new javax.swing.JTextField();
        AreaTT = new javax.swing.JTextField();
        nombrePRO = new javax.swing.JTextField();
        direccionn = new javax.swing.JTextField();
        latitud = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id__lugarrr = new javax.swing.JTextField();
        longitud = new javax.swing.JTextField();
        estadoo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizarTec.setText("Actualizar");
        actualizarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarTecActionPerformed(evt);
            }
        });
        jPanel1.add(actualizarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 170, 60));

        id__predio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__predioActionPerformed(evt);
            }
        });
        jPanel1.add(id__predio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, 40));

        nombrePRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePREActionPerformed(evt);
            }
        });
        jPanel1.add(nombrePRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 180, 40));

        AreaTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTTActionPerformed(evt);
            }
        });
        jPanel1.add(AreaTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 180, 40));
        jPanel1.add(nombrePRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 180, 40));

        direccionn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionnActionPerformed(evt);
            }
        });
        jPanel1.add(direccionn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, 40));

        latitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latitudActionPerformed(evt);
            }
        });
        jPanel1.add(latitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 180, 40));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Actualizar predio");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 390, 60));

        id__lugarrr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id__lugarrrActionPerformed(evt);
            }
        });
        jPanel1.add(id__lugarrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 180, 40));

        longitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudActionPerformed(evt);
            }
        });
        jPanel1.add(longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 180, 40));

        estadoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadooActionPerformed(evt);
            }
        });
        jPanel1.add(estadoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarTecActionPerformed
    try {
        // Obtener los valores del formulario
        int idPredio = Integer.parseInt(id__predio.getText().trim());
        String nombrePredio = nombrePRE.getText().trim();
        double areaTotal = Double.parseDouble(AreaTT.getText().trim());
        String nombrePropietario = nombrePRO.getText().trim();
        String direccion = direccionn.getText().trim();
        double coordenadasLat = Double.parseDouble(latitud.getText().trim());
        double coordenadasLon = Double.parseDouble(longitud.getText().trim());
        int idLugar = Integer.parseInt(id__lugarrr.getText().trim());
        String estado = estadoo.getText().trim();

        // Validar campos obligatorios
        if (nombrePredio.isEmpty() || nombrePropietario.isEmpty() || direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Por favor completa todos los campos obligatorios.",
                "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Crear el controlador
        PredioController predioController = new PredioController();

        // Llamar al método de actualización
        boolean actualizado = predioController.actualizarPredio(
                idPredio, 
                nombrePredio,
                areaTotal,
                nombrePropietario,
                direccion,
                coordenadasLat,
                coordenadasLon,
                idLugar,
                estado
        );

        // Mostrar resultado
        if (actualizado) {
            JOptionPane.showMessageDialog(this,
                "✅ Predio actualizado correctamente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);

            if (onPredioActualizado != null) {
                onPredioActualizado.run(); // refrescar tabla
            }

            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                "❌ Error al actualizar el predio.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Error: Los campos numéricos deben contener solo números.",
            "Error de formato", JOptionPane.ERROR_MESSAGE);
        System.out.println("❌ Error de número: " + e.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
            "Ocurrió un error al actualizar el predio.",
            "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_actualizarTecActionPerformed

    private void id__predioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__predioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__predioActionPerformed

    private void AreaTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaTTActionPerformed

    private void direccionnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionnActionPerformed

    private void nombrePREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePREActionPerformed

    private void latitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudActionPerformed

    private void id__lugarrrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id__lugarrrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id__lugarrrActionPerformed

    private void longitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudActionPerformed

    private void estadooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadooActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarPredio(0,"",0.0,"","",0.0,0.0,0,"",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaTT;
    private javax.swing.JButton actualizarTec;
    private javax.swing.JTextField direccionn;
    private javax.swing.JTextField estadoo;
    private javax.swing.JTextField id__lugarrr;
    private javax.swing.JTextField id__predio;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField latitud;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField nombrePRE;
    private javax.swing.JTextField nombrePRO;
    // End of variables declaration//GEN-END:variables
}
