/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PredioController;
import modelo.LugarProduccion;
import modelo.LugarProduccionDAO;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author omaci
 */
public class CrearPredio extends javax.swing.JFrame {
    private Runnable onPredioGuardado;
    private final List<Integer> lugarProIds = new ArrayList<>();

    /**
     * Creates new form CrearCliente
     */
    public CrearPredio(Runnable onPredioGuardado ) {
        initComponents();
        setLocationRelativeTo(null);
        this.onPredioGuardado = onPredioGuardado;
        cargarCombos();
    }
    
    private void cargarCombos() {
        cboLugar.removeAllItems();
        lugarProIds.clear();
        LugarProduccionDAO tdao = new LugarProduccionDAO();
        for (LugarProduccion p : tdao.listarLugaresConProductor()) {
            cboLugar.addItem(p.getDepartamento());
            lugarProIds.add(p.getId_lugar());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NombrePropi = new javax.swing.JTextField();
        AreaT = new javax.swing.JTextField();
        Direccionn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nombrePR = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        latitud = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        longitud = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboLugar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(NombrePropi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 180, 40));

        AreaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaTActionPerformed(evt);
            }
        });
        jPanel1.add(AreaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 180, 40));

        Direccionn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionnActionPerformed(evt);
            }
        });
        jPanel1.add(Direccionn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 180, 40));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 170, 60));

        nombrePR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePRActionPerformed(evt);
            }
        });
        jPanel1.add(nombrePR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, 40));

        jLabel2.setText("Nombre del predio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setText("Area total (Hectarioas)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setText("Nombre del propietario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jLabel5.setText("Direccion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jLabel6.setText("id lugar de produccion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        latitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latitudActionPerformed(evt);
            }
        });
        jPanel1.add(latitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 180, 40));

        jLabel7.setText("Cordenadas (Latitud)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        longitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longitudActionPerformed(evt);
            }
        });
        jPanel1.add(longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 180, 40));

        jLabel8.setText("Cordenadas (Longitud)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Añadir predio");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 310, 60));

        jPanel1.add(cboLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreaTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String nombrePredio = nombrePR.getText().trim();
            double areaTotal = Double.parseDouble(AreaT.getText().trim());
            String nombrePropietario = NombrePropi.getText().trim();
            String direccion = Direccionn.getText().trim();
            double coordenadasLat = Double.parseDouble(latitud.getText().trim());
            double coordenadasLon = Double.parseDouble(longitud.getText().trim());
            
            // Validar campos obligatorios
            if (nombrePredio.isEmpty() || nombrePropietario.isEmpty() || direccion.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Por favor completa todos los campos obligatorios.",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int idxP = cboLugar.getSelectedIndex();
            if (idxP < 0) {
                JOptionPane.showMessageDialog(this, "Seleccione Lugar de produccion.");
                return;
            }
            
            int idLugar = lugarProIds.get(idxP);
            
            // Crear controlador
            PredioController predioController = new PredioController();

            // Intentar agregar lugar
            int exito = predioController.agregarPredioAuto(
                    nombrePredio, 
                    areaTotal, 
                    nombrePropietario, 
                    direccion, 
                    coordenadasLat, 
                    coordenadasLon, 
                    idLugar,
                    "ACTIVO"
            );

            if (exito > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "✅ Predio creada. ID " + exito);
                if (onPredioGuardado != null) onPredioGuardado.run();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al crear el Predio.");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Error: Los campos numéricos deben contener solo números.",
                "Error de formato", JOptionPane.ERROR_MESSAGE);
            System.out.println("❌ Error de número: " + e.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Ocurrió un error al guardar un predio.",
                "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DireccionnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionnActionPerformed

    private void nombrePRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePRActionPerformed

    private void latitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latitudActionPerformed

    private void longitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPredio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPredio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPredio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPredio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPredio(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AreaT;
    private javax.swing.JTextField Direccionn;
    private javax.swing.JTextField NombrePropi;
    private javax.swing.JComboBox<String> cboLugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField latitud;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField nombrePR;
    // End of variables declaration//GEN-END:variables
}
