/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import controlador.LugarProduccionController;
import modelo.Productor;
import modelo.ProductorDAO;
/**
 *
 * @author omaci
 */
public class CrearLugarPro extends javax.swing.JFrame {
    private Runnable onLugarProGuardado;
    private final List<Integer> productorIds = new ArrayList<>();

    public CrearLugarPro(Runnable onLugarProGuardado) {
        initComponents();
        setLocationRelativeTo(null);
        this.onLugarProGuardado = onLugarProGuardado;
        cargarCombos();
    }
    
    private void cargarCombos() {
        cboProductor.removeAllItems();
        productorIds.clear();
        // Técnicos (nombre completo)
        ProductorDAO tdao = new ProductorDAO();
        for (Productor p : tdao.listarProductoresActivos()) {
            cboProductor.addItem(p.getPrimer_nombre());
            productorIds.add(p.getId_productor());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        veredaa = new javax.swing.JTextField();
        municipioo = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        departamentoo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboProductor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(veredaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 180, 40));

        municipioo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipiooActionPerformed(evt);
            }
        });
        jPanel1.add(municipioo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 180, 40));

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        jPanel1.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 180, 40));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 180, 60));

        departamentoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentooActionPerformed(evt);
            }
        });
        jPanel1.add(departamentoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 180, 40));

        jLabel2.setText("Departamento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setText("Municipio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel4.setText("Vereda");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel5.setText("Cantidad maxima");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel6.setText("Productor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Añadir lugar de produccion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 610, 60));

        jPanel1.add(cboProductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void municipiooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipiooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipiooActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String departamento  = departamentoo.getText().trim();
            String municipio     = municipioo.getText().trim();
            String vereda        = veredaa.getText().trim();
            int cantidadMaxima   = Integer.parseInt(cantidad.getText().trim());
            

            if (departamento.isEmpty() || municipio.isEmpty() || vereda.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Por favor completa todos los campos obligatorios.",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (cantidadMaxima <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad máxima debe ser > 0.");
                return;
            }
            
            int idxP = cboProductor.getSelectedIndex();
            if (idxP < 0) {
                JOptionPane.showMessageDialog(this, "Seleccione productor.");
                return;
            }
            
            int idProductor = productorIds.get(idxP);

            LugarProduccionController ctrl = new LugarProduccionController();
            
            int nuevoId = ctrl.agregarLugarAuto(departamento,municipio,vereda,cantidadMaxima,idProductor);
            if (nuevoId > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "✅ Lugar de pproduccion creada. ID " + nuevoId);
                if (onLugarProGuardado != null) onLugarProGuardado.run();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al crear el lugar de produccion.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Los campos numéricos (cantidad máxima deben ser números válidos.",
                "Error de formato", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, iae.getMessage(), "Validación", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar el lugar.", "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void departamentooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentooActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLugarPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLugarPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLugarPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLugarPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearLugarPro(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> cboProductor;
    private javax.swing.JTextField departamentoo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField municipioo;
    private javax.swing.JTextField veredaa;
    // End of variables declaration//GEN-END:variables
}
