/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.util.ArrayList;
import java.util.List;

import controlador.ObservacionesController;
import controlador.FuncionarioICAController;
import controlador.InspeccionFitosanitariaController;
import modelo.InspeccionFitosanitaria;
import modelo.FuncionarioICA;

/**
 *
 * @author omaci
 */
public class CrearObservacion extends javax.swing.JFrame {
    private ObservacionesController observacionesController;
    private Runnable onObservacionGuardada;

    private final List<Integer> inspeccionIds  = new ArrayList<>();
    private final List<Integer> funcionarioIds = new ArrayList<>();
    
    private static final DateTimeFormatter FMT_YMD =
        DateTimeFormatter.ofPattern("uuuu-MM-dd").withResolverStyle(ResolverStyle.STRICT);


    public CrearObservacion(Runnable onObservacionGuardada) {
        initComponents();
        setLocationRelativeTo(null);
        this.onObservacionGuardada = onObservacionGuardada;
        this.observacionesController = new ObservacionesController();
        cargarCombos();
    }
    
    /* ===================== VALIDAR FECHA ===================== */

    private boolean validarFechaCampo(JTextField campo, String etiqueta) {
        String s = campo.getText().trim();
        if (s.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "La " + etiqueta + " es obligatoria.",
                "Fecha inválida",
                JOptionPane.WARNING_MESSAGE
            );
            campo.requestFocus();
            return false;
        }
        try {
            LocalDate.parse(s, FMT_YMD);
            return true;
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this,
                "Formato inválido en " + etiqueta + ": \"" + s + "\".\n" +
                "Usa yyyy-MM-dd (ej. 2025-11-09).",
                "Fecha inválida",
                JOptionPane.WARNING_MESSAGE
            );
            campo.requestFocus();
            return false;
        }
    }
    
    private void cargarCombos() {
        cboInspeccion.removeAllItems();
        cboFuncionario.removeAllItems();
        inspeccionIds.clear();
        funcionarioIds.clear();

        // 1) Inspecciones para escoger a cuál pertenece la observación
        InspeccionFitosanitariaController inspCtrl = new InspeccionFitosanitariaController();
        for (InspeccionFitosanitaria insp : inspCtrl.listarConTecnicoEIncidencia()) {
            // texto amigable: "ID 10 - Lote 3 - 2025-11-10"
            String etiqueta = "ID " + insp.getId_inspeccion()
                            + " - Lote " + insp.getNumero_lote()
                            + " - " + insp.getFecha_inspeccion();
            cboInspeccion.addItem(etiqueta);
            inspeccionIds.add(insp.getId_inspeccion());
        }

        // 2) Funcionarios ICA
        FuncionarioICAController funcCtrl = new FuncionarioICAController();
        for (FuncionarioICA f : funcCtrl.obtenerFuncionariosActivos()) {
            String nombreCompleto = f.getPrimer_nombre() + " " + f.getPrimer_apellido();
            cboFuncionario.addItem(nombreCompleto);
            funcionarioIds.add(f.getId_funcionario());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        cboInspeccion = new javax.swing.JComboBox<>();
        cboFuncionario = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObsercaiocnes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 170, 60));

        jLabel6.setText("Funcionario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel7.setText("Observaciones");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Añadir observacion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 430, 60));

        jLabel8.setText("Fecha de la observacion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel9.setText("Numero de la inspeccion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 40));

        jPanel1.add(cboInspeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 40));

        jPanel1.add(cboFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 40));

        txtObsercaiocnes.setColumns(20);
        txtObsercaiocnes.setRows(5);
        jScrollPane1.setViewportView(txtObsercaiocnes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 240, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String fecha = txtFecha.getText().trim();
            String texto = txtObsercaiocnes.getText().trim();

            if (!validarFechaCampo(txtFecha, "Fecha de la observación")) return;

            if (texto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El texto de la observación es obligatorio.");
                return;
            }

            int idxInsp = cboInspeccion.getSelectedIndex();
            int idxFunc = cboFuncionario.getSelectedIndex();
            if (idxInsp < 0 || idxFunc < 0) {
                JOptionPane.showMessageDialog(this, "Seleccione inspección y funcionario.");
                return;
            }

            int idInspeccion = inspeccionIds.get(idxInsp);
            int idFuncionario = funcionarioIds.get(idxFunc);

            String error = observacionesController.crear(
                    fecha,
                    texto,
                    idInspeccion,
                    idFuncionario
            );

            if (error == null) {
                JOptionPane.showMessageDialog(this, "✅ Observación registrada.");
                if (onObservacionGuardada != null) onObservacionGuardada.run();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, error, "Error al crear", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar la observación.");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearObservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearObservacion(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboFuncionario;
    private javax.swing.JComboBox<String> cboInspeccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextArea txtObsercaiocnes;
    // End of variables declaration//GEN-END:variables
}
