/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PlagaController;
import javax.swing.JOptionPane;

/**
 *
 * @author omaci
 */
public class CrearPlaga extends javax.swing.JFrame {
    //private String idusuario;
    private Runnable onPlagaGuardado;
    

    /**
     * Creates new form CrearCliente
     */
    public CrearPlaga(Runnable onPlagaGuardado ) {
        initComponents();
        setLocationRelativeTo(null);
        this.onPlagaGuardado = onPlagaGuardado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombrecom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nombrecien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombrecom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecomActionPerformed(evt);
            }
        });
        jPanel1.add(nombrecom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 180, 40));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 170, 60));

        nombrecien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecienActionPerformed(evt);
            }
        });
        jPanel1.add(nombrecien, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 180, 40));

        jLabel2.setText("Nombre cientifico");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel3.setText("Nombre comun");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel4.setText("Descripcion ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Añadir plaga");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 290, 60));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 400, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombrecomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String nombreCientifica = nombrecien.getText().trim();
            String nombreComun      = nombrecom.getText().trim();
            String descripcion      = jTextArea1.getText().trim();

            // Validaciones básicas en la vista
            if (nombreCientifica.isEmpty() || nombreComun.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this,
                    "Por favor completa Nombre científico y Nombre común."
                );
                return;
            }

            PlagaController plagaController = new PlagaController();

            // VALIDAR DUPLICADO POR NOMBRE CIENTÍFICO
            if (plagaController.existeNombreCientifico(nombreCientifica)) {
                JOptionPane.showMessageDialog(
                    this,
                    "Ya existe una plaga con nombre científico: " + nombreCientifica + "."
                );
                nombrecien.requestFocus();
                return;
            }

            // Crear la plaga (el ID lo genera Oracle vía secuencia)
            boolean creada = plagaController.agregarPlaga(
                nombreCientifica,
                nombreComun,
                descripcion
            );

            if (creada) {
                JOptionPane.showMessageDialog(this, "Plaga creada exitosamente.");

                if (onPlagaGuardado != null) {
                    onPlagaGuardado.run(); // refrescar tabla
                }

                dispose();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "No se pudo crear la plaga. Verifica los datos o revisa la consola."
                );
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Ocurrió un error al guardar la plaga."
            );
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombrecienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPlaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPlaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPlaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPlaga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPlaga(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nombrecien;
    private javax.swing.JTextField nombrecom;
    // End of variables declaration//GEN-END:variables
}
