/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.LoteController;
import modelo.CultivoDAO;              // ajusta el paquete si difiere
import modelo.LugarProduccionDAO;     // ajusta el paquete si difiere
import modelo.Cultivo;
import modelo.LugarProduccion;

import javax.swing.*;
import java.util.List;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;

/**
 *
 * @author omaci
 */
public class CrearLote extends javax.swing.JFrame {
    //private String idusuario;
    private Runnable onLoteGuardado;
    private java.util.List<Integer> cultivoIds = new java.util.ArrayList<>();
    private java.util.List<Integer> lugarIds   = new java.util.ArrayList<>();
    
    private static final DateTimeFormatter FMT_YMD =
        DateTimeFormatter.ofPattern("uuuu-MM-dd").withResolverStyle(ResolverStyle.STRICT);

    private boolean validarFechaCampo(JTextField campo, String etiqueta) {
        String s = campo.getText().trim();
        if (s.isEmpty()) return true; // permitir vacío en fecha_eliminacion
        try {
            LocalDate.parse(s, FMT_YMD);
            return true;
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this,
                "Formato inválido en " + etiqueta + ": \"" + s + "\".\n" +
                "Usa yyyy-MM-dd (ej. 2025-11-09).",
                "Fecha inválida",
                JOptionPane.WARNING_MESSAGE
            );
            campo.requestFocus();
            return false;
        }
    }
    
    private static final String PLACEHOLDER = "— Selecciona estado —";

    private void cargarEstadosFenologicos() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem(PLACEHOLDER);              // índice 0 => placeholder
        jComboBox1.addItem("Siembra");
        jComboBox1.addItem("Germinación");
        jComboBox1.addItem("Crecimiento vegetativo");
        jComboBox1.addItem("Floración");
        jComboBox1.addItem("Fructificación");
        jComboBox1.addItem("Cosecha");
        jComboBox1.addItem("Reposo");
        jComboBox1.setSelectedIndex(0);
    }

    public CrearLote(Runnable onLoteGuardado) {
        initComponents();
        setLocationRelativeTo(null);
        this.onLoteGuardado = onLoteGuardado;
        cargarCombos();
        cargarEstadosFenologicos();
        jLabel10.setVisible(false);
        txtFechaEliminacion.setVisible(false);
    }
    
    private void cargarCombos() {
        cboCultivo.removeAllItems();
        cboLugar.removeAllItems();
        cultivoIds.clear();
        lugarIds.clear();

        // === Cultivos ===
        CultivoDAO cdao = new CultivoDAO();
        java.util.List<Cultivo> cultivos = cdao.listarCultivos();
        for (Cultivo c : cultivos) {
            String label = c.getNombre_especie() + " (ID " + c.getId_cultivo() + ")";
            cboCultivo.addItem(label);
            cultivoIds.add(c.getId_cultivo());   // índice del combo -> id
        }

        // === Lugares ===
        LugarProduccionDAO ldao = new LugarProduccionDAO();
        java.util.List<LugarProduccion> lugares = ldao.listarLugaresProduccion();
        for (LugarProduccion l : lugares) {
            String label = l.getDepartamento() + " (ID " + l.getId_lugar() + ")";
            cboLugar.addItem(label);
            lugarIds.add(l.getId_lugar());       // índice del combo -> id
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFechaEliminacion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtAreaSiembra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAreaTotal = new javax.swing.JTextField();
        txtFechaSiembra = new javax.swing.JTextField();
        cboLugar = new javax.swing.JComboBox<>();
        cboCultivo = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFechaEliminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaEliminacionActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaEliminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 100, 40));

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 170, 60));

        txtAreaSiembra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaSiembraActionPerformed(evt);
            }
        });
        jPanel1.add(txtAreaSiembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 180, 40));

        jLabel5.setText("Area total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel6.setText("Lugar de produccion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel7.setText("Area de siembra");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Añadir lote");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 240, 60));

        jLabel8.setText("Estado fenologico");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel9.setText("Fecha de siembra");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel10.setText("Fecha de eliminacion");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel11.setText("Cultivo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        txtAreaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtAreaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 180, 40));

        txtFechaSiembra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaSiembraActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaSiembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 180, 40));

        jPanel1.add(cboLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 180, 40));

        jPanel1.add(cboCultivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 180, 40));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            double areaTotal   = Double.parseDouble(txtAreaTotal.getText().trim());
            double areaSiembra = Double.parseDouble(txtAreaSiembra.getText().trim());
            String estadoFenologico = (String) jComboBox1.getSelectedItem();
            String fSiembra    = txtFechaSiembra.getText().trim();     // yyyy-MM-dd
            String fElimina    = txtFechaEliminacion.getText().trim(); // opcional

            int idxCultivo = cboCultivo.getSelectedIndex();
            int idxLugar   = cboLugar.getSelectedIndex();
            
            // Validar selección
            if (estadoFenologico == null || estadoFenologico.equals(PLACEHOLDER)) {
                JOptionPane.showMessageDialog(this, "Selecciona el estado fenológico.");
                jComboBox1.requestFocus();
                return;
            }
            
            if (!validarFechaCampo(txtFechaSiembra, "Fecha de siembra")) return;
            if (!validarFechaCampo(txtFechaEliminacion, "Fecha de eliminación")) return;

            if (areaTotal <= 0) {
                JOptionPane.showMessageDialog(this, "El área total debe ser mayor que 0.");
                return;
            }
            if (areaSiembra < 0) {
                JOptionPane.showMessageDialog(this, "El área de siembra no puede ser negativa.");
                return;
            }
            if (areaSiembra > areaTotal) {
                JOptionPane.showMessageDialog(this,
                    "El área de siembra no puede ser mayor que el área total.\n" +
                    "Revísalo: siembra = " + areaSiembra + " | total = " + areaTotal);
                return;
            }
            if (idxCultivo < 0 || idxLugar < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar Cultivo y Lugar.");
                return;
            }
            int idCultivo = cultivoIds.get(idxCultivo);
            int idLugar   = lugarIds.get(idxLugar);

            if (estadoFenologico.isEmpty() || fSiembra.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Estado fenológico y fecha siembra son obligatorios.");
                return;
            }

            LoteController ctrl = new LoteController();
            int nuevoId = ctrl.agregarLoteAuto(
                areaTotal, areaSiembra, estadoFenologico, fSiembra,
                fElimina.isEmpty() ? null : fElimina,
                idCultivo, idLugar
            );
            
            if (nuevoId > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "✅ Lote creado con número " + nuevoId + ".");
                if (onLoteGuardado != null) onLoteGuardado.run();
                dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "❌ Error al crear el lote.");
            }
        } catch (NumberFormatException nfe) {
            javax.swing.JOptionPane.showMessageDialog(this, "Áreas deben ser numéricas (usa punto decimal).");
        } catch (IllegalArgumentException iae) {
            javax.swing.JOptionPane.showMessageDialog(this, iae.getMessage());
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar el lote.");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAreaSiembraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaSiembraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaSiembraActionPerformed

    private void txtAreaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaTotalActionPerformed

    private void txtFechaSiembraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaSiembraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaSiembraActionPerformed

    private void txtFechaEliminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEliminacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEliminacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearLote(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCultivo;
    private javax.swing.JComboBox<String> cboLugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAreaSiembra;
    private javax.swing.JTextField txtAreaTotal;
    private javax.swing.JTextField txtFechaEliminacion;
    private javax.swing.JTextField txtFechaSiembra;
    // End of variables declaration//GEN-END:variables
}
