/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.util.ArrayList;
import java.util.List;

import controlador.InspeccionFitosanitariaController;
import modelo.LoteDAO;
import modelo.TecnicoOficialDAO;
import modelo.Lote;
import modelo.TecnicoOficial;

/**
 *
 * @author omaci
 */
public class CrearInspeccion extends javax.swing.JFrame {
    //private String idusuario;
    private Runnable onInspeccionGuardado;
    private final List<Integer> loteIds    = new ArrayList<>();
    private final List<Integer> tecnicoIds = new ArrayList<>();
    
    private static final DateTimeFormatter FMT_YMD =
        DateTimeFormatter.ofPattern("uuuu-MM-dd").withResolverStyle(ResolverStyle.STRICT);

    private boolean validarFechaCampo(JTextField campo, String etiqueta) {
        String s = campo.getText().trim();
        if (s.isEmpty()) return true; // permitir vacío en fecha_eliminacion
        try {
            LocalDate.parse(s, FMT_YMD);
            return true;
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this,
                "Formato inválido en " + etiqueta + ": \"" + s + "\".\n" +
                "Usa yyyy-MM-dd (ej. 2025-11-09).",
                "Fecha inválida",
                JOptionPane.WARNING_MESSAGE
            );
            campo.requestFocus();
            return false;
        }
    }

    public CrearInspeccion(Runnable onInspeccionGuardado) {
        initComponents();
        setLocationRelativeTo(null);
        this.onInspeccionGuardado = onInspeccionGuardado;
        cargarCombos();
    }
    
    private void cargarCombos() {
        cboLote.removeAllItems();
        cboTecnico.removeAllItems();
        loteIds.clear();
        tecnicoIds.clear();

        // Lotes (solo necesitamos el número de lote)
        LoteDAO ldao = new LoteDAO();
        for (Lote l : ldao.listarLote()) {
            cboLote.addItem("Lote " + l.getNumero_lote());
            loteIds.add(l.getNumero_lote());
        }

        // Técnicos (nombre completo)
        TecnicoOficialDAO tdao = new TecnicoOficialDAO();
        for (TecnicoOficial t : tdao.listarTecnicosActivos()) {
            cboTecnico.addItem(t.getPrimer_nombre());
            tecnicoIds.add(t.getNumero_registro());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtAfectadas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRevisadas = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        cboLote = new javax.swing.JComboBox<>();
        cboTecnico = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 170, 60));

        txtAfectadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAfectadasActionPerformed(evt);
            }
        });
        jPanel1.add(txtAfectadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 180, 40));

        jLabel5.setText("Plantas revisadas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel6.setText("Tecnico");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel7.setText("Plantas afectadas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Añadir inspeccion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 390, 60));

        jLabel8.setText("Fecha de la inspeccion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel9.setText("Numero del lote");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        txtRevisadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRevisadasActionPerformed(evt);
            }
        });
        jPanel1.add(txtRevisadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 180, 40));

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 180, 40));

        jPanel1.add(cboLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 180, 40));

        jPanel1.add(cboTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int revisadas = Integer.parseInt(txtRevisadas.getText().trim());
            int afectadas = Integer.parseInt(txtAfectadas.getText().trim());
            String fecha  = txtFecha.getText().trim();

            if (!validarFechaCampo(txtFecha, "Fecha de la inspeccion")) return;
            
            if (revisadas < 0) { JOptionPane.showMessageDialog(this, "Revisadas debe ser ≥ 0."); return; }
            if (afectadas < 0) { JOptionPane.showMessageDialog(this, "Afectadas debe ser ≥ 0."); return; }
            if (afectadas > revisadas) {
                JOptionPane.showMessageDialog(this, "Afectadas no puede ser mayor que Revisadas.");
                return;
            }
            int idxL = cboLote.getSelectedIndex();
            int idxT = cboTecnico.getSelectedIndex();
            if (idxL < 0 || idxT < 0) {
                JOptionPane.showMessageDialog(this, "Seleccione lote y técnico.");
                return;
            }
            int numeroLote = loteIds.get(idxL);
            int idTecnico  = tecnicoIds.get(idxT);
            
            InspeccionFitosanitariaController controller = new InspeccionFitosanitariaController();

            int nuevoId = controller.crearAuto(revisadas, afectadas, fecha, numeroLote, idTecnico);
            if (nuevoId > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "✅ Inspección creada. ID " + nuevoId);
                if (onInspeccionGuardado != null) onInspeccionGuardado.run();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Error al crear la inspección.");
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Revisadas/Afectadas deben ser enteros.");
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, iae.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar.");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAfectadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAfectadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAfectadasActionPerformed

    private void txtRevisadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRevisadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRevisadasActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearInspeccion(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboLote;
    private javax.swing.JComboBox<String> cboTecnico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAfectadas;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtRevisadas;
    // End of variables declaration//GEN-END:variables
}
