/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.InspeccionFitosanitariaController;
import modelo.InspeccionFitosanitaria;
import javax.swing.*;
import javax.swing.table.*;
import java.util.List;

/**
 *
 * @author ESTUDIANTE
 */
class TablaInspeccion extends javax.swing.JFrame {
    private InspeccionFitosanitariaController inspeccionFitosanitariaController;

    public TablaInspeccion() {
        initComponents();
        inspeccionFitosanitariaController = new InspeccionFitosanitariaController();
        setLocationRelativeTo(null);
        cargarInspecciones();
    }
    
     private void cargarInspecciones() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Fecha");
        modelo.addColumn("Revisadas");
        modelo.addColumn("Afectadas");
        modelo.addColumn("Incidencia (%)");
        modelo.addColumn("Nivel alerta");
        modelo.addColumn("N° Lote");
        modelo.addColumn("Técnico");

        List<InspeccionFitosanitaria> lista = inspeccionFitosanitariaController.listarConTecnicoEIncidencia();
        for (InspeccionFitosanitaria i : lista) {
            // Incidencia en UI (si tu POJO no la tiene):
            double inc = 0.0;
            if (i.getPlantas_revisadas() > 0) {
                inc = (i.getPlantas_afectadas() * 100.0) / i.getPlantas_revisadas();
            }
            Object[] fila = {
                i.getId_inspeccion(),
                i.getFecha_inspeccion(),         // "yyyy-MM-dd"
                i.getPlantas_revisadas(),
                i.getPlantas_afectadas(),
                i.getNivel_alerta(),
                i.getNivel_alerta(),
                i.getNumero_lote(),
                i.getNombre_tecnico()            // viene del JOIN del DAO
            };
            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botoncrear = new javax.swing.JButton();
        botoneditar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 87, 830, 360));

        botoncrear.setText("Crear");
        botoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearActionPerformed(evt);
            }
        });
        jPanel1.add(botoncrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 270, 40));

        botoneditar.setText("Editar");
        botoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneditarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 270, 40));

        botoneliminar.setText("Eliminar");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 270, 40));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Inspecciones fitosanitarias");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 580, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearActionPerformed
        CrearInspeccion crear = new CrearInspeccion(this::cargarInspecciones);
        crear.setVisible(true);
    }//GEN-LAST:event_botoncrearActionPerformed

    private void botoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneditarActionPerformed
        int viewRow = jTable1.getSelectedRow();
        if (viewRow == -1) { JOptionPane.showMessageDialog(this, "Seleccione una inspección."); return; }

        int row = jTable1.convertRowIndexToModel(viewRow);
        int id            = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
        String fecha      = String.valueOf(jTable1.getModel().getValueAt(row, 1));
        int revisadas     = Integer.parseInt(jTable1.getModel().getValueAt(row, 2).toString());
        int afectadas     = Integer.parseInt(jTable1.getModel().getValueAt(row, 3).toString());
        String nivel      = String.valueOf(jTable1.getModel().getValueAt(row, 5)); // solo informativo
        int numeroLote    = Integer.parseInt(jTable1.getModel().getValueAt(row, 6).toString());
        String nombreTec  = String.valueOf(jTable1.getModel().getValueAt(row, 7));

         ActualizarInspeccion actualizar = new ActualizarInspeccion(
            id, revisadas, afectadas, fecha, numeroLote, /* idTecnico: lo resolvemos por combo */ 0,
            this::cargarInspecciones
        );
        actualizar.setVisible(true);
    }//GEN-LAST:event_botoneditarActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        int viewRow = jTable1.getSelectedRow();
        if (viewRow == -1) { JOptionPane.showMessageDialog(this, "Seleccione una inspección."); return; }
        int row = jTable1.convertRowIndexToModel(viewRow);
        int id = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());

        int res = JOptionPane.showConfirmDialog(this, "¿Eliminar esta inspección?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            if (inspeccionFitosanitariaController.eliminar(id)) {
                JOptionPane.showMessageDialog(this, "✅ Inspección eliminada.");
                cargarInspecciones();
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo eliminar.");
            }
        }
    }//GEN-LAST:event_botoneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaInspeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaInspeccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncrear;
    private javax.swing.JButton botoneditar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
