/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.TecnicoOficialController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import modelo.TecnicoOficial;

/**
 *
 * @author ESTUDIANTE
 */
class TablaTecnico extends javax.swing.JFrame {
    private TecnicoOficialController tecnicoOficialController;
    
    private String rol;
    
    public TablaTecnico(String rol) {
        initComponents();
        tecnicoOficialController = new TecnicoOficialController();
        setLocationRelativeTo(null);
        cargarTecnicos();
        this.rol = rol;
    }
    
     private void cargarTecnicos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Numero Registro");
        modelo.addColumn("Número Identificación");
        modelo.addColumn("Tipo Identificación");
        modelo.addColumn("Primer Nombre");
        modelo.addColumn("Segundo Nombre");
        modelo.addColumn("Primer Apellido");
        modelo.addColumn("Segundo Apellido");
        modelo.addColumn("Dirección");
        modelo.addColumn("Celular");
        modelo.addColumn("Correo");
        modelo.addColumn("Estado");

        List<TecnicoOficial> tecnicos = tecnicoOficialController.listarTecnicos();
        for (TecnicoOficial p : tecnicos) {
            Object[] fila = {
                p.getNumero_registro(),
                p.getNumero_identificacion(),
                p.getTipo_identificacion(),
                p.getPrimer_nombre(),
                p.getSegundo_nombre(),
                p.getPrimer_apellido(),
                p.getSegundo_apellido(),
                p.getDireccion(),
                p.getCelular(),
                p.getCorreo(),
                p.getEstado()
            };
            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botoncrear = new javax.swing.JButton();
        botoneditar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 107, 840, 340));

        botoncrear.setText("Crear");
        botoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearActionPerformed(evt);
            }
        });
        jPanel1.add(botoncrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 270, 40));

        botoneditar.setText("Editar");
        botoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneditarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 270, 40));

        botoneliminar.setText("Eliminar");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 270, 40));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Tecnicos oficiales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 400, 60));

        volver.setText("Volver a el menu");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearActionPerformed
        CrearTecnico crear = new CrearTecnico(this::cargarTecnicos);
        crear.setVisible(true);
    }//GEN-LAST:event_botoncrearActionPerformed

    private void botoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneditarActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) { JOptionPane.showMessageDialog(this, "Seleccione un técnico para editar."); return; }

        // Por si hay sorter activo
        int modelRow = jTable1.convertRowIndexToModel(fila);
        DefaultTableModel m = (DefaultTableModel) jTable1.getModel();

        int numeroRegistro       = Integer.parseInt(m.getValueAt(modelRow, 0).toString());
        long numeroIdentificacion= Long.parseLong(m.getValueAt(modelRow, 1).toString());
        String tipoIdentificacion= String.valueOf(m.getValueAt(modelRow, 2));
        String primerNombre      = String.valueOf(m.getValueAt(modelRow, 3));
        String segundoNombre     = m.getValueAt(modelRow, 4) != null ? String.valueOf(m.getValueAt(modelRow, 4)) : "";
        String primerApellido    = String.valueOf(m.getValueAt(modelRow, 5));
        String segundoApellido   = m.getValueAt(modelRow, 6) != null ? String.valueOf(m.getValueAt(modelRow, 6)) : "";
        String direccion         = String.valueOf(m.getValueAt(modelRow, 7));
        long celular             = Long.parseLong(m.getValueAt(modelRow, 8).toString());
        String correo            = String.valueOf(m.getValueAt(modelRow, 9));
        String estado            = String.valueOf(m.getValueAt(modelRow, 10));

        ActualizarTecnico actualizar = new ActualizarTecnico(
            numeroRegistro, numeroIdentificacion, tipoIdentificacion,
            primerNombre, segundoNombre, primerApellido, segundoApellido,
            direccion, celular, correo, estado, this::cargarTecnicos
        );
        actualizar.setVisible(true);
    }//GEN-LAST:event_botoneditarActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        int viewRow = jTable1.getSelectedRow();
        if (viewRow == -1) { JOptionPane.showMessageDialog(this, "Seleccione un técnico para eliminar."); return; }

        int row = jTable1.convertRowIndexToModel(viewRow);
        int numeroRegistro = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());

        int res = JOptionPane.showConfirmDialog(this, "¿Está seguro de inactivar este técnico?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            if (tecnicoOficialController.desactivarTecnicoSeguro(numeroRegistro)) {
                JOptionPane.showMessageDialog(this, "✅ Técnico inactivado.");
                cargarTecnicos();
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo inactivar el técnico. Verifique dependencias (INSPECCION).");
            }
        }
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        Opciones opciones = new Opciones(rol);  // ⬅ volvemos con el mismo rol
        opciones.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaTecnico("ADMIN").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncrear;
    private javax.swing.JButton botoneditar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
