/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.PredioController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import modelo.Predio;

/**
 *
 * @author ESTUDIANTE
 */
class TablaPredio extends javax.swing.JFrame {
     private PredioController predioController;
     //private int idProductor;
    /**
     * Creates new form Tabla
     */
    public TablaPredio(/*int idProductor*/) {
        initComponents();
        setLocationRelativeTo(null);
        predioController = new PredioController();
        cargarPredio();
    }
    
    private void cargarPredio() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Predio");
        modelo.addColumn("Nombre Predio");
        modelo.addColumn("Área Total");
        modelo.addColumn("Propietario");
        modelo.addColumn("Dirección");
        modelo.addColumn("Coordenada Lat");
        modelo.addColumn("Coordenada Lon");
        modelo.addColumn("ID Lugar");
        modelo.addColumn("Estado");

        // Obtener lista desde el controlador
        List<Predio> predios = predioController.listarPrediosConLugar();
        for (Predio p : predios) {
            Object[] fila = {
                p.getId_predio(),
                p.getNombre_predio(),
                p.getArea_total(),
                p.getNombre_propietario(),
                p.getDireccion(),
                p.getCoordenadas_lat(),
                p.getCoordenadas_lon(),
                (p.getLugar_label()== null ? "" : p.getLugar_label()),
                p.getEstado()
            };
            modelo.addRow(fila);
        }

        // Asignar modelo a la tabla
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botoncrear = new javax.swing.JButton();
        botoneditar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 87, 850, 360));

        botoncrear.setText("Crear");
        botoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearActionPerformed(evt);
            }
        });
        jPanel1.add(botoncrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, 270, 40));

        botoneditar.setText("Editar");
        botoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneditarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 270, 40));

        botoneliminar.setText("Eliminar");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 270, 40));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Predios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 190, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearActionPerformed
        CrearPredio crear = new CrearPredio(this::cargarPredio);
        crear.setVisible(true);
    }//GEN-LAST:event_botoncrearActionPerformed

    private void botoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneditarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un predio para editar.");
            return;
        }
        int idPredio = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        String nombrePredio = jTable1.getValueAt(fila, 1).toString();
        double areaTotal = Double.parseDouble(jTable1.getValueAt(fila, 2).toString());
        String nombrePropietario = jTable1.getValueAt(fila, 3).toString();
        String direccion = jTable1.getValueAt(fila, 4).toString();
        double coordenadasLat = Double.parseDouble(jTable1.getValueAt(fila, 5).toString());
        double coordenadasLon = Double.parseDouble(jTable1.getValueAt(fila, 6).toString());
        String nombreLu  = String.valueOf(jTable1.getModel().getValueAt(fila, 7));
        //int idLugar = Integer.parseInt(jTable1.getValueAt(fila, 7).toString());
        String estado = jTable1.getValueAt(fila, 8).toString();

        // Abrir la vista de actualización
        ActualizarPredio actualizar = new ActualizarPredio(
                idPredio,
                nombrePredio,
                areaTotal,
                nombrePropietario,
                direccion,
                coordenadasLat,
                coordenadasLon,
                0,
                estado,
                this::cargarPredio
        );

        actualizar.setVisible(true);
    }//GEN-LAST:event_botoneditarActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un predio para eliminar.");
            return;
        }
        int modelRow = jTable1.convertRowIndexToModel(fila);
        int idPredio = (Integer) jTable1.getModel().getValueAt(modelRow, 0);

        int confirmacion = JOptionPane.showConfirmDialog(
            this, "¿Está seguro de inactivar este predio?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            predioController.inactivarPredio(idPredio);
            cargarPredio();
        }
    }//GEN-LAST:event_botoneliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaPredio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaPredio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaPredio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaPredio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaPredio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncrear;
    private javax.swing.JButton botoneditar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
