/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.LugarProduccionController;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import modelo.LugarProduccion;

/**
 *
 * @author ESTUDIANTE
 */
class TablaLugarPr extends javax.swing.JFrame {
    private LugarProduccionController lugarProduccionController;

    public TablaLugarPr() {
        initComponents();
        setLocationRelativeTo(null);
        lugarProduccionController = new LugarProduccionController();
        cargarLugaresPr();
    }
    
     private void cargarLugaresPr() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Lugar");
        modelo.addColumn("Departamento");
        modelo.addColumn("Municipio");
        modelo.addColumn("Vereda");
        modelo.addColumn("Cantidad Máxima");
        modelo.addColumn("Productor");     // ← nombre completo

        List<LugarProduccion> lugares = lugarProduccionController.listarLugaresConProductor();
        for (LugarProduccion p : lugares) {
            Object[] fila = {
                p.getId_lugar(),
                p.getDepartamento(),
                p.getMunicipio(),
                p.getVereda(),
                p.getCantidad_maxima(),
                (p.getProductor_nombre() == null ? "" : p.getProductor_nombre())
            };
            modelo.addRow(fila);
        }
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botoncrear = new javax.swing.JButton();
        botoneditar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 238, 208));

        jPanel1.setBackground(new java.awt.Color(237, 218, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 87, 870, 360));

        botoncrear.setText("Crear");
        botoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearActionPerformed(evt);
            }
        });
        jPanel1.add(botoncrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 270, 40));

        botoneditar.setText("Editar");
        botoneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneditarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 270, 40));

        botoneliminar.setText("Eliminar");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botoneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 270, 40));

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Lugares de produccion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 500, 60));

        volver.setText("Volver a el menu");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearActionPerformed
        CrearLugarPro crear = new CrearLugarPro(this::cargarLugaresPr);
        crear.setVisible(true);
    }//GEN-LAST:event_botoncrearActionPerformed

    private void botoneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneditarActionPerformed
        int viewRow = jTable1.getSelectedRow();
        if (viewRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un lugar de producción para editar.");
            return;
        }
        int row = jTable1.convertRowIndexToModel(viewRow);
        int idLugar         = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
        String departamento = jTable1.getModel().getValueAt(row, 1).toString();
        String municipio    = jTable1.getModel().getValueAt(row, 2).toString();
        String vereda       = jTable1.getModel().getValueAt(row, 3).toString();
        int cantidadMaxima  = Integer.parseInt(jTable1.getModel().getValueAt(row, 4).toString());
        String nombrePro  = String.valueOf(jTable1.getModel().getValueAt(row, 5));

        ActualizarLugarPro actualizar = new ActualizarLugarPro(
            idLugar, departamento, municipio, vereda, cantidadMaxima,0, this::cargarLugaresPr
        );
        actualizar.setVisible(true);
    }//GEN-LAST:event_botoneditarActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        int viewRow = jTable1.getSelectedRow();
        if (viewRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un lugar de producción para eliminar.");
            return;
        }
        int row = jTable1.convertRowIndexToModel(viewRow);
        int idLugar = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());

        int res = JOptionPane.showConfirmDialog(
            this, "¿Está seguro de eliminar este lugar de producción?", 
            "Confirmar", JOptionPane.YES_NO_OPTION
        );
        if (res == JOptionPane.YES_OPTION) {
            boolean ok = lugarProduccionController.eliminarLugar(idLugar);
            if (ok) {
                JOptionPane.showMessageDialog(this, "✅ Lugar eliminado.");
                cargarLugaresPr();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "❌ No se pudo eliminar. Verifique dependencias (PREDIO O LOTE).");
            }
        }
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        Opciones opciones = new Opciones();
        opciones.setVisible(true);
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaLugarPr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaLugarPr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaLugarPr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaLugarPr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaLugarPr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncrear;
    private javax.swing.JButton botoneditar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
